name: Gatekeeper

on:
  pull_request:
    branches:
      - main

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      repo:write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: whatsapp_web_listener/package-lock.json

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::201893381538:role/GitHubRole
        role-session-name: GitHubActionsSession
    - name: Set up Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry self add 'poethepoet[poetry_plugin]'

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install dependencies
      run: |
        poetry install
        npm install -g aws-cdk

    - name: Install dependencies in whatsapp-web-listener folder
      run: |
        pushd whatsapp_web_listener
        npm install
        popd

    - name: Run gatekeeper script
      run: poetry poe gate_ci
    - name: Create coverage report in PR
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        output: file
        format: markdown
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

