name: Gatekeeper

on:
  pull_request:
    branches:
      - main

jobs:
  gatekeeper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry self add 'poethepoet[poetry_plugin]'

    - name: Install dependencies
      run: |
        poetry install

    - name: Install dependencies in whatsapp-web-listener folder
      run: |
        pushd whatsapp_web_listener
        npm install
        popd

    - name: Run gatekeeper script
      run: poetry poe gate_ci
    - name: Create coverage report in PR
      uses: 5monkeys/cobertura-action@master

